spring:
  application:
    name: spring-test
  mail:
    host: smtp.gmail.com
    port: 587
    username: 1004mapa9802@gmail.com
    password: 1
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.mail: DEBUG
    com.sun.mail.smtp: DEBUG